---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
#  - name: bento/ubuntu-14.04
#  - name: bento/centos-7.1
#  - name: bento/debian-7.8
  - name: bento/fedora-21
#  - name: bento/freebsd-10.2

suites:
  - name: default
    run_list:
      - recipe[chef-cuneiform::_common]
      - recipe[chef-cuneiform::default]
    attributes:
