---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  
verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-9
  - name: fedora-28
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[chef-cuneiform::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
